### ISSUE TITLE
WordPress/Ghost importer

### ISSUE THREAD

**Issue by claviska** [Leafpub/leafpub#1]
Ability to import posts, pages, tags/categories, and media items from other platforms:
- [ ] WordPress
- [ ] Ghost
- Others? Suggestions welcome.

**Comment by neo22s** [comment]
Sure, you would have like a universal importer, where you specify the format so if anyone comes from any other platform they may be able to format the file as you require and then import to you ;)

**Comment by claviska** [comment]
The biggest problem I foresee is not being able to import media. Neither Ghost nor WordPress export media files, so I'm not sure how that will work.

**Comment by neo22s** [comment]
Maybe you can create something like a "migration" tool, where client specifies the root of the WP installation, and from there you can read the DB config and the image folder. And migrate it to whatever your structure is ;)

This can be done as a background task or similar.

**Comment by Fermain** [comment]
I recently exported a SquareSpace site to wordpress using this [plugin](https://wordpress.org/plugins/import-external-images/), the approach was to crawl the target site for images and reupload them into the wordpress media browser. I think this would a potential solution for WordPress -> Postleaf

**Comment by claviska** [comment]
I was thinking that this would probably end up as a plugin. That's the approach [Ghost took](https://wordpress.org/plugins/ghost/), although I'm not sure if they handle media or not.

Has the WP REST API landed [yet]? That would make it a lot easier.

**Comment by karsasmus** [comment]
The WP REST API isn't in the core. It's a plugin.

We could use WordPress' export function so you needn't write a WordPress plugin for the export.
The WordPress XML contains users/tags/posts/media and so we can parse the file and import the data.
We could download the media files via curl.

I think, it's easier to use the available export solutions than writing a plugin for a foreign system.

**Comment by karsasmus** [comment]
Hello @claviska , 
here are the mockups for the importer.
**Step 1**
Choose the system to import. (After submitting the system the import class is instantiated via factory pattern)
![step 1](https://cloud.githubusercontent.com/assets/6382544/17942387/72d72502-6a37-11e6-9612-5b3508bef9b2.png)

**Step 2**
Select the XML file.
![step 2](https://cloud.githubusercontent.com/assets/6382544/17942390/72db7616-6a37-11e6-8b18-dab3b5e15933.png)

**Step 3**
After uploading and parsing the xml file, you'll see the content you're able to import. Just check the data to import.
![step 3](https://cloud.githubusercontent.com/assets/6382544/17942389/72d8b7be-6a37-11e6-8f05-218d4ac0f738.png)

**Step 4**
You'll see the import status.
![step 4](https://cloud.githubusercontent.com/assets/6382544/17942388/72d83136-6a37-11e6-8e2e-4149b91b011c.png)

**Step 5**
No Picture, import completed

**Comment by claviska** [comment]
I think we can simplify this a bit:

- We can probably auto-detect whether which platform the backup is from using the XML/JSON file, so that removes step 1.
- If this is going to be a first-party plugin, I'd like to minimize the options so it's less for us to maintain. If someone is migrating their blog/website, they probably want to migrate everything (e.g. all users, tags, posts, etc.) So I'd say import everything by default. Users can always delete what they don't want later.

There should be a couple options for WP though:

- Tags (radio button)
  - Ability to import categories as tags (and drop WP tags)
  - Ability to import tags as tags (and drop WP categories)
  - Maybe the ability to import categories AND tags as tags
- Content / uploads (radio button)
  - Import content only
  - Import content and uploads

What do you think?

**Comment by karsasmus** [comment]
Sounds good to me.

I'm a little undecided, if the user should be able to choose between content only or content and media. 
Blogposts with missing images could annoy the user.

Wordpress doesn't export the user's password.
Here's an example node:

`<wp:author>
  <wp:author_id>5</wp:author_id>
  <wp:author_login><![CDATA[username]]></wp:author_login>
  <wp:author_email><![CDATA[username@gmail.com]]></wp:author_email>
  <wp:author_display_name><![CDATA[Username]]></wp:author_display_name>
  <wp:author_first_name><![CDATA[User]]></wp:author_first_name>
  <wp:author_last_name><![CDATA[Name]]></wp:author_last_name>
</wp:author>`

We parse the wp:author-nodes, import the authors and use the 'api/login/recover' route to generate a new password and send a credential email.

What do you think?

**Comment by icaromh** [comment]
@karsasmus could take a couple hours to export and import all the images from a huge database. My girlfriend, for example, has a Fashion Blog early 2010, kinda 5gb of images storaged at wp.com

I think thats a good idea import images apart. And after do some `UPDATE SET url=newurl` or something like that.

**Comment by claviska** [comment]
> I'm a little undecided, if the user should be able to choose between content only or content and media. 

Correct, @icaromh. Giving them the option would let them manually copy things over which can be much quicker for bigger sites.

> Wordpress doesn't export the user's password.

I guess for security reasons but, in my opinion, backup files themselves can be considered sensitive. 🤔

> We parse the wp:author-nodes, import the authors and use the 'api/login/recover' route to generate a new password and send a credential email.

It's easy enough to do this with a simple `User::update()`, but the API could be a good approach too if you find it robust enough as-is. (It will be evolved more as the project matures.)

This is a very complicated task to tackle, so props for the effort. I'll have more time to dedicate to this in about a week.

**Comment by karsasmus** [comment]
Whoa, you're right, I haven't thought at such a big amount of pictures/media.

**Comment by karsasmus** [comment]
I added a [proposal](https://github.com/Postleaf/postleaf/pull/71) for this functionality.

I implemented a factory pattern to get the right import class (wordpress, ghost).
If we want to import a tumblr or a blogspot blog, we only need to add such an ImportClass and don't need to concern about the initialisation.

**Comment by claviska** [comment]
It's looking good, but I really think this should be a plugin. How do you feel about me creating a separate repo so we can work on parsing Ghost and WP data?

Once we get that far, we can see what we need to add to core to get the appropriate data pulled in, and what hooks we'll need to mold this into a plugin?

**Comment by karsasmus** [comment]
Sounds good to me.

Parsing the XML data isn't a big deal, I think.
Cleaning the Wordpress content from shortcodes and updating the href/src data will be a little bit tricky.

**Comment by oleteacher** [comment]
Saw GitHub email about release of Leafpub 1.2-beta2:

Notable changes
Updates to Wordpress importer

Pretty sure going to fell stupid:), but where is the WP importer and how to use it?

Go easy on me, very first time user...

**Comment by trentyarwood** [comment]
domain.tld/admin/import/

This tripped me up for a while, too. 

:)

**Comment by oleteacher** [comment]
Thank you @trentyarwood!

I was looking everywhere in docs for this. On my way now:)
