### ISSUE TITLE
Changed slug is not saved

### ISSUE THREAD

**Issue by jstemberg** [Leafpub/leafpub#112]
When the slug of the published post is changed in editor and "Save" button is clicked, new slug is not saved and post has always the old slug. There is no way to change it.

**Comment by karsasmus** [comment]
Hi @jstemberg,

thanks for posting.
Bug is fixed in [1.1.8](https://github.com/Leafpub/leafpub/releases/download/1.1.8/leafpub-1.1.8.zip)

**Comment by jstemberg** [comment]
Hi,

Thank you for fixing the bug and thank you for all your work on Leafpub! It
is amazing publishing tool - so simple and so fast.

I will promote it as much as possible :-)

Jan Štemberg

2017-04-03 8:45 GMT+02:00 Marc <notifications@github.com>:
