### ISSUE TITLE
Slug for non english characters

### ISSUE THREAD

**Issue by jstemberg** [Leafpub/leafpub#113]
Now, if main headline of the post contains non english chars (ěščřýááé....), these chars are removed form slug when it is generated. It would be better to transform these chars by this way: č→c, é→e... If these chars are removed, the meaning of the slug does not make a sense.
It would help many users using languages as Latin, Greek, Turkish, Russian, Czech, Polish...
There are many PHP function for this reason for example [https://gist.github.com/sgmurphy/3098978](https://gist.github.com/sgmurphy/3098978)

**Comment by karsasmus** [comment]
I'm open for a PR ;-)

**Comment by karsasmus** [comment]
This feature will be in V1.2 :smiley:

**Comment by jstemberg** [comment]
Perfect :-)

Thank you

2017-04-03 10:25 GMT+02:00 Marc <notifications@github.com>:
