### ISSUE TITLE
Error 500 after update from 1.1.7 to 1.1.8

### ISSUE THREAD

**Issue by jstemberg** [Leafpub/leafpub#114]
There is an 500 error after update from 1.1.7 to 1.1.8. The update was realised by replacing "index.php" and content of the "source" folder.

**Comment by karsasmus** [comment]
Create a folder named `log` in your root folder and set permissions to `755`.
This should fix it.

**Comment by jstemberg** [comment]
It seems there is an another error. This is the message from Apache log:
`[Mon Apr 03 10:37:37.866077 2017] [php7:notice] [pid 11408:tid 1832] [client 127.0.0.1:56873] Slim Application Error:\r\nType: Error\r\nMessage: Class 'Leafpub\\Models\\PostMeta' not found\r\nFile: C:\\dev\\www\\repos\\smartchords\\Blog\\source\\classes\\Models\\Post.php\r\nLine: 1128\r\nTrace: #0 C:\\dev\\www\\repos\\smartchords\\Blog\\source\\classes\\Models\\Post.php(1169): Leafpub\\Models\\Post::getPostMeta(5)\n#1 C:\\dev\\www\\repos\\smartchords\\Blog\\source\\classes\\Models\\Post.php(235): Leafpub\\Models\\Post::normalize(Array)\n#2 C:\\dev\\www\\repos\\smartchords\\Blog\\source\\classes\\Models\\Post.php(852): Leafpub\\Models\\Post::getOne('homepage')\n#3 C:\\dev\\www\\repos\\smartchords\\Blog\\source\\classes\\Controller\\ThemeController.php(57): Leafpub\\Models\\Post::render('homepage')\n#4 [internal function]: Leafpub\\Controller\\ThemeController->customHomepage(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response), Array)\n#5 C:\\dev\\www\\repos\\smartchords\\Blog\\source\\vendor\\slim\\slim\\`

**Comment by jstemberg** [comment]
Yes! Now, it works perfectly! Thank you for fixing.
