### ISSUE TITLE
Caption box on images prevents centre justify

### ISSUE THREAD

**Issue by trentyarwood** [Leafpub/leafpub#118]
### Issue Summary

Images can be centre justified in the image sidebar or in the editor.

Opening the sidebar, clicking the "add a caption" checkbox left-justifies the picture, prevents centre justification of the image in the editor.

### Steps to Reproduce

Add image.
Click "Centre Justify"
Click image properties button
Select "add a caption"
Click Submit
Attempt to re-centre-justify picture in editor.

### Additional info

- Leafpub version:   1.2b1
- PHP version: 7.0.15
- Affected browsers: Chrome
- Operating system:  Host: Ubuntu 16.04; view: Win 10

See: The xkcd in this post: https://postleaf.yarwood.id.au/concern-trolling-101

**Comment by karsasmus** [comment]
Hi @trentyarwood ,

this bug was fixed with the newest release of Range (https://github.com/Leafpub/range/blob/master/css/theme.css#L694)

The latest beta of Leafpub ( [beta4](https://github.com/Leafpub/leafpub/releases/download/1.2-beta4/leafpub-1.2-beta4.zip) ) includes Range 1.1.0 :slightly_smiling_face:

**Comment by trentyarwood** [comment]
Ahah. I customised range with a new font and a couple of minor changes, so haven't been updating the themes. Cheers.

**Comment by trentyarwood** [comment]
Still doing this with new range and b4:

Before caption box:
![temp1](https://cloud.githubusercontent.com/assets/10393897/25055752/1244e3ae-21a8-11e7-8d9e-54d2c4b3aaec.png)

After caption box:

![temp2](https://cloud.githubusercontent.com/assets/10393897/25055757/2037bd06-21a8-11e7-8983-c1e966278d9d.jpg)

**Comment by karsasmus** [comment]
Hi @trentyarwood ,

you're right, sorry for that. I've fixed the bug on master.
A workaround until the next beta will be released:

- Remove caption
- Remove img alignment
- submit
- reopen dialog
- Add caption and alignment
- submit

Your pic with caption should be aligned left now.
