### ISSUE TITLE
Donations via liberapay

### ISSUE THREAD

**Issue by oliverpool** [Leafpub/leafpub#120]
Hi,

you mention on the [support page](https://www.leafpub.org/support) that "*it (leafpub) takes a lot of time and money to develop, maintain, and support.*"

I would like to support your work, by doing more than using it: donating a little bit :-)

There is a nice (french) open-source platform for recurring micro-donations: Liberapay.com.
It allows you to create a team and the members of the team decide how they split the donations (one can also give directly to one person).

They eat there own dog food, since they don't get money on the transactions (the fees are for the Mango costs), but also have a page to receive donations https://liberapay.com/Liberapay/.

I created a (small) pledge for the leafpub github account: https://liberapay.com/on/github/Leafpub/.
To receive it, you only have to signup and link your github account (to prove that you belong to the leafpub team).

All the best and thanks again for this great software !

**Comment by karsasmus** [comment]
Thank you for support 🙂 
But here in Germany I must tell every donation to the tax authorities and pay taxes.
So it's possible that I have to pay more taxes then someone donates.
Therefore I've to close this issue without receiving your donation 🙁
