### ISSUE TITLE
Font Awesome Pro SVG Engine

### ISSUE THREAD

**Issue by trentyarwood** [Leafpub/leafpub#127]
I'm interested in using the SVG framework in FontAwesome pro for a project I'm working on. 

From FA's instructions: 

> Grab the base Font Awesome loader at /js/fontawesome.js.
Grab one or more of the styles (ex: /js/packs/solid.js) in the /js/packs directory.
Place these files in your project static files.
Include them in the <head> of your document.
Reference Font Awesome icons (using the inventory for easy copying/pasting) in the <body> of your document.
Example: 
```
<head>
  <script defer src="/js/packs/solid.js"></script>
  <script defer src="/js/fontawesome.js"></script>
</head>
```
My question is:  do these go in the LP javascript folder (/source/assets/js/) or the theme one (/content/themes/range/js) ?

I imagine it's the range folder, and do we then insert the script call into /partials/header.hbs ?

Sorry for spamming the GIT this week;  I do my blog tinkering in focused blocks then not for ages! (Also: the community discourse is down and redirects here)

**Comment by karsasmus** [comment]
Hi @trentyarwood ,
you need to put these files into Range's js folder and add them into partials/header.hbs :smile:

**Comment by trentyarwood** [comment]
Got it working, cheers!
