### ISSUE TITLE
Website & documentation

### ISSUE THREAD

**Issue by nalecu** [Leafpub/leafpub#132]
Hi, Marc. I noticed https://www.leafpub.org/ redirects here, to Leafpub's repo.
What I would actually need help with is some kind of access to the "Documentation" section of the website.
Do you, by any chance, plan to include it in the repo? or maybe some other way?

Thank you!

**Comment by micalm** [comment]
@nalecu, you can access a cached copy of the docs via Google cache.
Just Google e.g. `cache:leafpub.org` to access that URL.

**Comment by nalecu** [comment]
@micalm nope, tried that, cache is to recent; it gave me the ideea of trying the wayback machine, but couldn't find anything of use.
I still hope @karsasmus will be able to help ...

**Comment by karsasmus** [comment]
Hi @nalecu 
I've copied the docs from the old homepage into the wiki section. :-)

**Comment by nalecu** [comment]
Thanks, Marc!
