### ISSUE TITLE
Can't install Leafpub on /Public_html

### ISSUE THREAD

**Issue by phonecompi** [Leafpub/leafpub#133]
Sory for my English before. I want to ask.

why I can't install leafpub in root domain (_/public_html_ or _domain.com_)? It's always 500 internal server error. But it fine to instal on _public_html/leafpub folder_ or _domain.com/leafpub_

**Comment by karsasmus** [comment]
Sorry, but there's an template for creating an issue.
What's your php/server/mySQL/Leafpub version?
Are there any server logs?

Without any further information it's impossible to know, why your server is raising an error 500...
