### ISSUE TITLE
Uploads (media) manager

### ISSUE THREAD

**Issue by claviska** [Leafpub/leafpub#38]
This issue is for planning out the uploads manager. Current thoughts:
- A dedicated section in the admin panel to manage uploads.
- A control that can attach to an input or button that lets users browse for uploaded items. This should include a search and the ability to delete items if privileges allow.
- The ability to tag files and search/sort by tag might be useful
- It might be useful to track which user uploads a file. Easy enough to do, and could make it easier to search/sort/delete your own files.
- Indicator to show if file is being used on a post or other part of the site
- Thumbnail previews of images

**Comment by karsasmus** [comment]
Added with [41ec0c](https://github.com/Leafpub/leafpub/commit/41ec0ce8d9b651466e96452c6af1045f43432259)
