### ISSUE TITLE
Ability to fetch resources with helpers

### ISSUE THREAD

**Issue by claviska** [Leafpub/leafpub#5]
We need some additional helpers to make templates more useful.
- [x] `{{#posts}}`
- [x] `{{#tags}}`
- [x] `{{#authors}}`

Example usage might look like this:

``` hbs
{{#posts author="bob" query="kittens" count="10" offset="0" sort="newest"}}
    {{#each posts}}
        ...
    {{/each}}
{{/posts}}
```

**Comment by karsasmus** [comment]
Added the 3 helpers.

## Helper `{{#posts}}`:
### available options:
* `author`
  The author's slug
* `count`
  Items per Page
* `query`
  Searchstring
* `sort` 
  newest or oldest

### Returned fields
* id
* slug
* created
* pub_date
* author
* title
* content
* image
* meta_title
* meta_description
* status
* page
* featured
* sticky

_If no option is present, the helper returns no data._

## Helper `{{#tags}}`
### available options:
* `query`
  Wildcard to search in slug an name and Description
* `count`
  Items per page
* `sort`
  newest or oldest
  
### Returned fields
* id
* created
* slug
* name
* description
* cover
* meta_title
* meta_description

_If no option is present, the helper returns no data._

## Helper `{{#authors}}`
### available options:
* `query`
  Wildcard to search the author's slug or name

### Returned fields
* slug
* name
* avatar
* post_count

_If no option is present, the helper returns all authors._
