### ISSUE TITLE
Backup exception not shown if long filenames exist

### ISSUE THREAD

**Issue by lucamariani** [Leafpub/leafpub#87]
### Issue Summary

Making a backup in postleaf-1.0.0-beta7 if any file whose name is longer than 100 characters exist breaks without warning the user about what's wrong (tar doesn't handle such filenames)
"The backup con not be done" message is correctly reported but the exception is not logged or prompted to user.
It's a cosmetic issue but I've spent some time to find out what's wrong in my backup.
### Steps to Reproduce
1. create a file in content/uploads/... with a filename having more than 100 chars
2. do a backup
### Additional info
- postleaf-1.0.0-beta7
- PHP version: 5.6.26-1~dotdeb+7.1 amd64
- Operating system: Debian 7.11

**Comment by karsasmus** [comment]
Fixed with the [media manager addition](41ec0c)
