### ISSUE TITLE
Optional SMTP wrapper for emails

### ISSUE THREAD

**Issue by claviska** [Leafpub/leafpub#9]
Emails are only sent [currently] for password resets, but they almost always end up in the spam folder when they come from `mail()`. Allowing users to configure an SMTP server will circumvent this problem.

**Comment by doughnet** [comment]
What about using swift?

http://swiftmailer.org/

it's a library that will cover all the basis:  Send emails using SMTP, sendmail, postfix or a custom Transport implementation of your own

**Comment by claviska** [comment]
I was thinking [PHPMailer](https://github.com/PHPMailer/PHPMailer), but I'm open to options. This isn't immediately on the list so there's time to discuss it.

**Comment by napolux** [comment]
One interface to rule them all, then we can write wrappers for every possible client (starting with PHPMailer and SwiftMailer

**Comment by claviska** [comment]
I think @napolux is right. Pretty much all the transactional email providers I checked (SparkPost, SendGrid, Mailgun, Mailjet, Postmark, and Campaign Monitor) support SMTP, but many also have direct API access. This might be better off as a plugin instead of core.

**Comment by karsasmus** [comment]
Added with [b1108c](https://github.com/Leafpub/leafpub/commit/b1108c8f8d1335b895bb98888efa91423850a7bb)
