### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by karsasmus** [Leafpub/leafpub#92]
Setting the site in maintenance mode for visitors and users < owner/admin

**Comment by karsasmus** [comment]
Added with [55e46839](https://github.com/Leafpub/leafpub/commit/55e46839fdf9894e85bc99eb015f1b1f27538cce)

**Comment by claviska** [comment]
Cool feature. Just a thought — would it be better to use the error page for the maintenance message (with custom title/message) than create a new template in each theme?

You could always do a quick check and include a different partial if you really need a unique maintenance page.

I'm mentioning it because it seems like a lot of design overhead for a feature that not everyone will use.

**Comment by karsasmus** [comment]
Thanks for your thoughts about this feature.

Let me share my thoughts about a separate maintenance template with you:

* I'd like to follow the `separation of concerns`-aspect, but that's just a really really small part
* As of my knowledge, end-users, who probably aren't devs or a designers, are more likely to open the theme folder, see the maintenance.hbs and know, that if they want to change the design of their maintenance page, this is the place to do the changes.
I thought it to be more intuitively than read the theme's manual, open `partials/maintenance.hbs` and do some changes in this partial, that gets rendered in the `error.hbs`

**Comment by claviska** [comment]
One error template can easily cover all use cases now and in the future (404 Not Found, 500 Internal Server Error, 503 Service Unavailable, etc.).

Passing the HTTP status code to the error template would be a more elegant way for theme designers to manage "maintenance mode" (which is really just an HTTP 503 error) and other errors in the future. What if there's another use case that gets added later on? Using the current convention, it would require all themes to support yet _another_ theme file (which is a breaking change) and  it would add even more clutter to the theme folder.

It may seem more intuitive to designers at a glance, but it's less maintainable from a development perspective. And if this becomes convention, you'll end up with a theme folder that looks [like this](https://github.com/WordPress/twentysixteen), which I would argue is even more confusing.

Using a single error page and then offering the ability (without the requirement) to branch errors into separate partials seems like a more logical approach. A basic example of `error.hbs` that supports 500, 503, and defaults to 404 might look like this:

```hbs
{{#is @request.http_code '500'}}
    {{> 'partials/internal-server-error'}}
{{/is}}

{{#is @request.http_code '503'}}
    {{> 'partials/service-unavailable'}}
{{/is}}

{{#is @request.http_code 'not in' '500,503'}}
     {{> 'partials/error-not-found'}}
{{/is}}
```

Granted, we could really use a chainable `is` helper to make this less verbose, but you get the idea.

Most importantly, now you can support _any_ HTTP status code without cluttering theme folders or introducing a breaking change that will affect every existing theme.

**Comment by karsasmus** [comment]
I totally understand your point of view.

I’ve always tended to keeping it simple which means as little logic as possible. The logic on the other hand is supposed to be in the controller or the `Error.php`.

But let's combine your excellent thoughts with my "simple" views and use of `Error.php`:
We use the theme.json.

We create an array after 'url', 'error_tempplates' for example, and define per key/value writing, which template to use.

`'error_templates:' {
	'404': 'partials/404.hbs',
	'503': 'partials/503.hbs',
	.
	.
	.
}`

In our `Error.php`, we get the respnonses HTTP Status Code and check if our actual theme has a template for the status code.

Yes --> render status template.
No --> render standard error.php

This way a designer is able to create/adding error templates without touching core files.

**Comment by claviska** [comment]
Sounds good and keeps things backwards compatible. 👍

**Comment by karsasmus** [comment]
Added with [c6943a4](https://github.com/Leafpub/leafpub/commit/c6943a4417a11c53b7414867ffba82f6dcee61cd)
