### ISSUE TITLE
Add classes to href in editor

### ISSUE THREAD

**Issue by karsasmus** [Leafpub/leafpub#93]
Create the possibility to add css classes to `<a>` - tags.

**Comment by icaromh** [comment]
Hi :D 

How it will work? I mean, it will be configured at settings? Add class when you click at "insert link"?

**Comment by karsasmus** [comment]
Hi, @icaromh,

yes, I thought of adding an input for the classes on the "insert link"-panel.

**Comment by icaromh** [comment]
@karsasmus 

something like [this plugin](http://learn.wpeditpro.com/insertedit-advanced-link-button/)?

I'm looking to contribute 😃

**Comment by claviska** [comment]
I imagine it would be a separate input field that merely reads/writes the link's class attribute. You could reference the `title` as an example of how it's done.

**Comment by karsasmus** [comment]
Awesome, thanks for the hint.
