### ISSUE TITLE
Weird margins in Dashboard

### ISSUE THREAD

**Issue by dawidxt** [Leafpub/leafpub#95]
I just had a test drive with a new release of LeafPub (version 8). My current website is powered by previous version 7. 

I noticed small issue of a dashboard look. I know its nothing big, but such small details makes something great. And I just want to let You know of it. 

I think that images will be enough to describe the issue without any additional words.
![new](https://cloud.githubusercontent.com/assets/13783466/20698856/2f929b78-b604-11e6-8f20-de44506929f3.jpg)
![old](https://cloud.githubusercontent.com/assets/13783466/20698859/3416a0a4-b604-11e6-9c22-b1dceb6c174a.jpg)

**Comment by karsasmus** [comment]
Hi @dawidxt ,

your're right, this margins shouldn't be there :slightly_smiling_face: 
Fixed in [19d9060](https://github.com/Leafpub/leafpub/commit/19d9060e02e406627324276e913865eb7c4f1e83)
